In [1]:
# Classes,Matplotlib,Pandas,Numpy & Scipy etc.

In [2]:
#classes
class Test():
    pass

In [3]:
a = Test()

In [4]:
type(a)

__main__.Test

In [18]:
class Animal():
    def __init__(self,colour,jump):
        self.colour = colour
        self.jump = jump
    
    def speaks(self,sound):
        print("I can speak {} and my colour is {}".format(sound,self.colour))

In [19]:
monkey = Animal("Brown","yes")

In [20]:
monkey.speaks("hoo")

I can speak hoo and my colour is Brown


In [21]:
monkey.colour

'Brown'

In [22]:
dog = Animal("Black","no")

In [23]:
dog.speaks('woof')

I can speak woof and my colour is Black


In [52]:
class Dog(Animal):   #Inheritance
    def __init__(self,breed,cost):
        Animal.__init__(self,"White","yes")
        self.breed = breed
        self.cost = cost
    def eat():
        print("I eat!")
    
    def __str__(self):  #Magic function
        return ("I am dog of breed {}".format(self.breed))
    
    def __len__(self): #Magic function
        return self.cost

In [53]:
d = Dog("Labrador",50)

In [54]:
d.speaks("woof")

I can speak woof and my colour is White


In [55]:
d.breed

'Labrador'

In [56]:
d.cost

50

In [57]:
print(d)

I am dog of breed Labrador


In [58]:
len(d)

50

In [59]:
import numpy as np

In [60]:
lst = [1,2,3]
lst2 = ['a','b','c']

arr1 = np.array(lst)
arr1

array([1, 2, 3])

In [61]:
type(arr1)

numpy.ndarray

In [62]:
arr2 = np.array(lst2)
arr2

array(['a', 'b', 'c'], dtype='<U1')

In [63]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
from numpy.random import rand

In [65]:
arr1 = rand(5)

In [67]:
type(arr1) #it is numpy array

numpy.ndarray

In [68]:
arr1

array([0.10045944, 0.45539222, 0.05207962, 0.30638975, 0.90752839])

In [69]:
arr2 = rand(3,4)
arr2

array([[0.7344411 , 0.41939578, 0.09699885, 0.68958594],
       [0.51065897, 0.94089736, 0.20919502, 0.12277114],
       [0.42301605, 0.76103469, 0.1771192 , 0.59476684]])

In [70]:
arr2.shape

(3, 4)

In [71]:
arr1.shape

(5,)

In [72]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr3 = np.arange(15)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
arr3.shape

(15,)

In [75]:
arr4 = arr3.reshape(3,5)

In [76]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
arr4[1,1] #find by indexes

6

In [79]:
arr4[1:,0:2]

array([[ 5,  6],
       [10, 11]])

In [80]:
arr1 = rand(30)

In [81]:
arr1

array([0.49385185, 0.75927753, 0.58284445, 0.22574464, 0.99388592,
       0.67505209, 0.29931946, 0.21572358, 0.03343879, 0.01582563,
       0.3647619 , 0.93076017, 0.40522403, 0.45772053, 0.5883789 ,
       0.69207743, 0.60871996, 0.8880355 , 0.60181884, 0.01425061,
       0.86773921, 0.92421995, 0.35771967, 0.8037019 , 0.59613545,
       0.98641966, 0.12563381, 0.54073108, 0.65682361, 0.80663567])

In [82]:
arr2 = arr1.reshape(5,6)

In [83]:
arr2

array([[0.49385185, 0.75927753, 0.58284445, 0.22574464, 0.99388592,
        0.67505209],
       [0.29931946, 0.21572358, 0.03343879, 0.01582563, 0.3647619 ,
        0.93076017],
       [0.40522403, 0.45772053, 0.5883789 , 0.69207743, 0.60871996,
        0.8880355 ],
       [0.60181884, 0.01425061, 0.86773921, 0.92421995, 0.35771967,
        0.8037019 ],
       [0.59613545, 0.98641966, 0.12563381, 0.54073108, 0.65682361,
        0.80663567]])

In [85]:
arr2[2:4,0:2] #3rd and 4th row & 1st and 2nd column

array([[0.40522403, 0.45772053],
       [0.60181884, 0.01425061]])

In [87]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [91]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [92]:
np.random.seed(12)

In [93]:
np.random.randint(1,100)  #whole grad group got 76 because of same seed

76

In [95]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [96]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
arr1*arr1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [98]:
arr1*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [99]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [100]:
arr1.max()

9

In [101]:
arr1.min()

0

In [102]:
arr1.argmax()

9

In [103]:
import pandas as pd

In [104]:
df = pd.DataFrame(np.random.randn(4,5),['a','b','c','d'],['u','w','x','y','z'])
df

u         w         x         y         z
a  1.050716 -0.151333  0.236029 -0.436550 -0.278310
b -0.089292 -0.484535 -0.237422 -0.794900  1.412418
c  0.873828 -0.039122 -0.378736 -0.333654  0.275939
d  0.609689 -0.055316  0.576118  1.363391  0.285748

In [105]:
df['w']

a   -0.151333
b   -0.484535
c   -0.039122
d   -0.055316
Name: w, dtype: float64

In [107]:
df[['x','z']]

x         z
a  0.236029 -0.278310
b -0.237422  1.412418
c -0.378736  0.275939
d  0.576118  0.285748

In [108]:
df.loc['a']

u    1.050716
w   -0.151333
x    0.236029
y   -0.436550
z   -0.278310
Name: a, dtype: float64

In [109]:
df.loc[['a','b']]

u         w         x        y         z
a  1.050716 -0.151333  0.236029 -0.43655 -0.278310
b -0.089292 -0.484535 -0.237422 -0.79490  1.412418

In [111]:
df.iloc[3]  #4th Row

u    0.609689
w   -0.055316
x    0.576118
y    1.363391
z    0.285748
Name: d, dtype: float64

In [112]:
df['w'] > 0

a    False
b    False
c    False
d    False
Name: w, dtype: bool

In [113]:
bool_val = df['w'] > 0
bool_val

a    False
b    False
c    False
d    False
Name: w, dtype: bool

In [114]:
df[(df['w'] > 0) & (df['y'] > 0)]

Empty DataFrame
Columns: [u, w, x, y, z]
Index: []

In [121]:
df

u         w         x         y         z  nex_column  new_column
a  1.050716 -0.151333  0.236029 -0.436550 -0.278310    0.084696    0.084696
b -0.089292 -0.484535 -0.237422 -0.794900  1.412418   -0.721957   -0.721957
c  0.873828 -0.039122 -0.378736 -0.333654  0.275939   -0.417858   -0.417858
d  0.609689 -0.055316  0.576118  1.363391  0.285748    0.520802    0.520802

In [122]:
df[['x','y']]

x         y
a  0.236029 -0.436550
b -0.237422 -0.794900
c -0.378736 -0.333654
d  0.576118  1.363391

In [123]:
df.loc[['c','d']]

u         w         x         y         z  nex_column  new_column
c  0.873828 -0.039122 -0.378736 -0.333654  0.275939   -0.417858   -0.417858
d  0.609689 -0.055316  0.576118  1.363391  0.285748    0.520802    0.520802

In [124]:
df[['x','y']].loc[['c','d']]

x         y
c -0.378736 -0.333654
d  0.576118  1.363391

In [125]:
df['new_column'] = df['w'] + df['x']
df

u         w         x         y         z  nex_column  new_column
a  1.050716 -0.151333  0.236029 -0.436550 -0.278310    0.084696    0.084696
b -0.089292 -0.484535 -0.237422 -0.794900  1.412418   -0.721957   -0.721957
c  0.873828 -0.039122 -0.378736 -0.333654  0.275939   -0.417858   -0.417858
d  0.609689 -0.055316  0.576118  1.363391  0.285748    0.520802    0.520802

In [126]:
df.drop('x',axis=1)

u         w         y         z  nex_column  new_column
a  1.050716 -0.151333 -0.436550 -0.278310    0.084696    0.084696
b -0.089292 -0.484535 -0.794900  1.412418   -0.721957   -0.721957
c  0.873828 -0.039122 -0.333654  0.275939   -0.417858   -0.417858
d  0.609689 -0.055316  1.363391  0.285748    0.520802    0.520802

In [127]:
df

u         w         x         y         z  nex_column  new_column
a  1.050716 -0.151333  0.236029 -0.436550 -0.278310    0.084696    0.084696
b -0.089292 -0.484535 -0.237422 -0.794900  1.412418   -0.721957   -0.721957
c  0.873828 -0.039122 -0.378736 -0.333654  0.275939   -0.417858   -0.417858
d  0.609689 -0.055316  0.576118  1.363391  0.285748    0.520802    0.520802

In [128]:
df.drop('x',axis=1,inplace=True)

In [129]:
df

u         w         y         z  nex_column  new_column
a  1.050716 -0.151333 -0.436550 -0.278310    0.084696    0.084696
b -0.089292 -0.484535 -0.794900  1.412418   -0.721957   -0.721957
c  0.873828 -0.039122 -0.333654  0.275939   -0.417858   -0.417858
d  0.609689 -0.055316  1.363391  0.285748    0.520802    0.520802